exp_name: 08Aug # Can be over-written by args
dataset: la
dataset_dir: ./citynetworks_data
results_dir: ./results
models_dir: ./models
method: sgformer
seed: 0
device: 0
train:
  epochs: 20000
  evaluation_window: 100
  lr: 5.e-4
  dropout: 0.2
  weight_decay: 1.e-5
  save_model: True
model:
  num_layers: 16
  hidden_channels: 64
  num_heads: 1
  gnn_type: GCN
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_act: True
  aggregate: add
  use_graph: True
  graph_weight: 0.8
  use_weight: False
  jump_knowledge: False
